### ISSUE TITLE
no pool config found

### ISSUE THREAD

**Issue by zikkuratti** [ajb413/comet-liquidator#2]
on a test and prod node i get every time after check 1000 1000 1000 387 ... im trying to delete MATICX but its still ruin, got some advices? also this wallet f3C4 leads me to StMATIC 

Checking for purchasable collateral
There is purchasable collateral
Error: getPoolConfig > no pool config found for 0x3A58a54C066FdC0f2D55FC9C89F0415C92eBf3C4
at getPoolConfig (C:\Users\zikkuratti\comet-liquidator\scripts\liquidation_bot\liquidateUnderwaterBorrowers.ts:257:11)

**Comment by zikkuratti** [comment]
i add [addresses.polygon.STMATIC.toLowerCase()]: {
     ...defaultPoolConfig,
     ...{
       exchange: Exchange.Uniswap,
       swapViaWeth: true,
       uniswapPoolFee: 500
     }
   },  STMATIC: '0x3A58a54C066FdC0f2D55FC9C89F0415C92eBf3C4',

**Comment by zikkuratti** [comment]
after  gasLimit: '30000000',
        gasPrice: '75',

he still cant see any sucess

**Comment by pamarthisai** [comment]
@zikkuratti  hi did you get any solution

**Comment by ajb413** [comment]
Error says that there isn't a pool config. This is because I made that repository before stmatic was a collateral on polygon cUSDCv3. So you'll need to add it yourself. Take a look at an existing asset like WBTC and use it to make new references to stmatic. https://github.com/ajb413/comet-liquidator/blob/master/scripts/liquidation_bot/liquidateUnderwaterBorrowers.ts#L54
